### ISSUE TITLE
Level restrictions

### ISSUE THREAD

**Issue by tmes970020** [spigot-gillesm/RPProfessions#10]
I cannot use crafted items to exceed level 26, but I can use commands to exceed level 26.

**Comment by spigot-gillesm** [comment]
Hi! You probably haven't set any recipes with a level cap option above 25.

For a recipe to give profession levels, you must check that level-gain is set to 1 (or more) and the level cap of the recipe is not too low:

```yaml
# Any recipe configuration ...
level-cap: 75 # The recipe won't give extra levels once the player has reached level 75
level-gain: 1 # One level gained per crafted item
```

If you still have an issue don't hesitate to ask for extra help. Otherwise I let you close this thread and I hope you're enjoying RPProfessions
