### ISSUE TITLE
Feature request - Oraxen

### ISSUE THREAD

**Issue by MattWillen** [spigot-gillesm/RPProfessions#3]
I'm not sure this is in the plugin yet, but it would be a game changer to have the possibility to use Oraxen items for anything that the plugin implements, instead of just for recipe results and ingredients.
This way we could have custom modeled workstations, profession items, fuels, etc.

The format could be something like Oraxen's default notation: `oraxen:item_name`.
The default workstation example, using Oraxen's items, would be something like:
``` yml
# The workstation ID (to be used in the profession configuration file)
ANVIL:
  # The actual in-game blocks that allow to open the crafting menu
  materials:
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - oraxen:my_anvil #Here is the oraxen block/furniture used as workstation!
  display-name: "&8Anvil"
  # The menu that is open when interacting with the listed materials
  station: ANVIL
  # The RPProfessions item needed to use the workstation
  tool: oraxen:my_hammer #Here is the oraxen item used as profession item!
```

Thanks in advance.
