### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LoaSamedi** [spigot-gillesm/RPProfessions#4]
Hello!
I was trying to create a custom potion, and when I check the wiki, it saids can be anything in the Receptacle section. But when I try to set an mmoitem as the ingrediant, it pops up an error in the console. It seems like the receptacle secitons only works with normal items. Am I set something wrong? If not, can you implement this feature in future update?
Thank you.

**Comment by spigot-gillesm** [comment]
Hi!

It is possible to use items from MythicMobs, MMOItems and Oraxen as a receptacle for your recipes:

```yaml
receptacle: mi:MY_MMOITEMS_POTION
```

Where 'MY_MMOITEMS_POTION' can be any item from MMOItems.

Full example:

```yaml
HEALING_POTION_III:
  material: POTION
  display-name: "&bPotion of Healing"
  station: BREWING_STAND
  category: POTION
  dynamic: true
  fuel-consumed: true
  potion-type: AWKWARD
  potion-effects:
    HEAL:
      amplifier: 2
  receptacle: mi:HEALTH_POTION_III
  reagent: GOLDEN_APPLE
  fuel: WEAK_INFUSER
  level-gain: 1
  level-cap: 50
```

I consider the issue resolved but I let you close it to confirm you got the help you needed.
