### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by HeinrichLivingston** [spigot-gillesm/RPProfessions#6]
Bought this a while ago, tried to setup the Blacksmith hammer via MMOItems to be used for the Anvil. It shows that it's linked all fine n dandy, but I can't open the Anvi UI. Not sure if it's my lack on knowledge for coding or if I pooched something... Love some help.

Cheers,

Heinrich.

**Comment by spigot-gillesm** [comment]
Hi!
Thank you for using RPProfessions!
Could you send me the content of your workstations.yml file so I can see if something is missing/wrong?

**Comment by HeinrichLivingston** [comment]
Yes of course!

`# The workstation ID (to be used in the profession configuration file)
ANVIL:
  # The actual in-game blocks that allow to open the crafting menu
  materials:
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  display-name: "&8Anvil"
  # The menu that is open when interacting with the listed materials
  station: ANVIL
  # The RPProfessions item needed to use the workstation
  tool: BLACKSMITH_HAMMER
FORGE:
  materials:
  - BLAST_FURNACE
  display-name: "&4Forge"
  station: FORGE
  # The block that must be next to the station in order to work
  fuel: LAVA`

**Comment by HeinrichLivingston** [comment]
This to my knowledge is the base file. I had created a blacksmith hammer already. Idk if I need to put "mi:" prior to the ID or not.

**Comment by spigot-gillesm** [comment]
Thanks for the information. I think the issue here is that you're directly using the MMOItem, and not the RPProfession item (that makes use of MMOItem). To be more precise, RPProfessions uses (hidden) IDs inside the items and when you click a station with an item, RPProfessions check the item id to decide whether or not you're using the right tool. So, when using the blacksmith hammer from MMOItems, RPProfessions cannot find said ID.
To make it work, you have to get the BLACKSMITH_HAMMER item **from RPProfessions**. You can use the '/rpp item get BLACKSMITH_HAMMER' command to get it, use the drop tables, use villager trades or make the item craftable. Another way I like is by using custom villagers (you can check Shopkeepers for that) and give them a trade for your tool (that, again, must be retrieved using RPProfessions). You can also make tools craftable with the vanilla crafting table (there's info on that in the wiki).

So, to clarify: The tool must come from the RPProfessions plugin.

You can add the hammer in your 'items/' folder, in your 'blacksmith.yml' file for example:

```yaml
# The anvil workstation's tool
BLACKSMITH_HAMMER:
  category: TOOL
  mmo-item: BLACKSMITH_HAMMER # You get the MMOItems named "BALCKSMITH_HAMMER"
```

And use the get command as given above.

Or, you can make it a craftable item in the crafting table:

```yaml
# The anvil workstation's tool
BLACKSMITH_HAMMER:
  category: TOOL
  # Any blacksmith can craft the hammer in a vanilla crafting station. This will then allow them to use the anvil for the advanced recipes
  station: WORKBENCH
  mmo-item: BLACKSMITH_HAMMER # You get the MMOItems named "BALCKSMITH_HAMMER"
  # A hammer shaped craft
  recipe:
    0: IRON_INGOT
    1: IRON_INGOT
    2: IRON_INGOT
    3: IRON_INGOT
    4: STICK
    5: IRON_INGOT
    7: STICK
```

But these are just examples. As long as the tool comes from RPProfessions (i.e. RPProfessions is the plugin that generated the item) it should work!

I hoped this helped!
